# .pre-commit-hooks.yaml
---
- id: validate-k8s
  name: Validate Kubernetes manifests
  entry: scripts/validate-k8s.sh
  language: script
  pass_filenames: true
  require_serial: true
  stages:
  - pre-commit
  files: '\.(ya?ml|yaml)$'
