---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: substituted
  namespace: ${NAMESPACE}
spec:
  replicas: ${REPLICA_COUNT}
  selector:
    matchLabels:
      app: substituted
  template:
    metadata:
      labels:
        app: substituted
    spec:
      containers:
      - name: app
        image: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
